x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile.airflow

  env_file:
    - .env

  environment:
    AIRFLOW__CORE__EXECUTOR: SequentialExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
    AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
    DS108_PROJECT_ROOT: /opt/airflow
    PYTHONPATH: /opt/airflow
    CDSAPI_URL: ${CDSAPI_URL:-https://cds.climate.copernicus.eu/api}
    CDSAPI_KEY: ${CDSAPI_KEY:-}

  volumes:
    - .:/opt/airflow
    - airflow_logs:/opt/airflow/logs

  user: "${AIRFLOW_UID:-50000}:0"
  restart: unless-stopped


services:
  airflow-init:
    <<: *airflow-common
    container_name: ds108_airflow_init
    restart: "no"
    command: >
      bash -c "
      mkdir -p /opt/airflow/data &&
      airflow db migrate &&
      airflow users list | grep -q admin ||
      airflow users create
      --username admin
      --password admin
      --email admin@example.com
      "

  airflow-webserver:
    <<: *airflow-common
    container_name: ds108_airflow_webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    ports:
      - "8081:8080"
    command: airflow webserver

  airflow-scheduler:
    <<: *airflow-common
    container_name: ds108_airflow_scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    command: airflow scheduler

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ds108_dashboard

    env_file:
      - .env

    environment:
      DS108_PROJECT_ROOT: /app
      PYTHONPATH: /app
      CDSAPI_URL: ${CDSAPI_URL:-https://cds.climate.copernicus.eu/api}
      CDSAPI_KEY: ${CDSAPI_KEY:-}

    volumes:
      - .:/app

    ports:
      - "8502:8501"

    command: streamlit run demo/app.py --server.address=0.0.0.0 --server.port=8501
    restart: unless-stopped


volumes:
  airflow_logs: