source:
  name: "nasa_power"
  base_url: "https://power.larc.nasa.gov/api/temporal"

request:
  community: "AG"
  format: "JSON"
  time_standard: "UTC"

date_range:
  start_date: "20150101"
  end_date: "20250824"

parameters:
  PRECTOTCORR: "precipitationCorrected"
  T2M: "temperature2m"
  T2M_MAX: "temperature2mMax"
  T2M_MIN: "temperature2mMin"
  T2MDEW: "dewPoint2m"
  TS: "earthSkinTemperature"
  RH2M: "relativeHumidity2m"
  QV2M: "specificHumidity2m"
  PS: "surfacePressure"
  WS10M: "windSpeed10m"
  WD10M: "windDirection10m"
  ALLSKY_SFC_SW_DWN: "shortwaveDownwardIrradiance"
  ALLSKY_SFC_LW_DWN: "longwaveDownwardIrradiance"
  GWETTOP: "surfaceSoilWetness"
  GWETROOT: "rootZoneSoilWetness"
  CLOUD_AMT: "cloudFraction"