source:
  name: "nasa_power"
  base_url: "https://power.larc.nasa.gov/api/temporal"

request:
  community: "AG"
  format: "JSON"
  time_standard: "UTC"

date_range:
  start_date: "20150101"
  end_date: "20251231"

parameters:
  daily:
    - "PRECTOTCORR"
    - "T2M"
    - "T2M_MAX"
    - "T2M_MIN"
    - "T2MDEW"
    - "TS"
    - "RH2M"
    - "QV2M"
    - "PS"
    - "WS10M"
    - "WD10M"
    - "ALLSKY_SFC_SW_DWN"
    - "ALLSKY_SFC_LW_DWN"
    - "GWETTOP"
    - "GWETROOT"
    - "CLOUD_AMT"